# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bbb88015d982eda278cc4f1256b6d4e1ced2243d8efded4efb91b49a5605b1528e846786aa16580fa70a83b4da1a030b21dbda0149e95a081ad112b6561a0f5

test:
  secret_key_base: 4f9122193d93d8ee449ee96bcce182f4e3f1d354e95770f69a83ef947b9da84c90569e0e4439c33d43cb4b2bcfb22f17c67e79a8d89ec15d94a5cea7215fecd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
